package com.sleeplessdog.matchthewords.backend.domain.models

enum class WordsGroupsList(val key: String) {
    ANIMALS("animals"),
    FOOD("food"),
    FAMILY("family"),
    CLOTHES("clothes"),
    PLACES("places"),
    TIME("time"),
    TRANSPORT("transport"),
    WORK("work"),
    HOUSE("house"),
    EDUCATION("education"),
    NATURE("nature"),
    EMOTIONS("emotions"),
    COLORS("colors"),
    NUMBERS("numbers"),
    ACTIONS("actions"),
    OBJECTS("objects"),
    ABSTRACT("abstract"),
    ENTERTAINMENT("entertainment"),
    COMMUNICATION("communication"),
    TRAVEL("travel"),
    HEALTH("health"),
    GENERAL_ADJECTIVES("general_adjectives"),
    GENERAL_ADVERBS("general_adverbs"),
    GENERAL_PRONOUNS("general_pronouns"),
    MISCELLANEOUS("miscellaneous"),
    BODY("body"),
    PROGRAMMING("programming"),
    DESIGN("design"),
    RANDOM("random"),
    USERS_DICTIONARY("users_dictionary");
}